In [36]:
#https://pytorch.org/hub/pytorch_vision_alexnet/
import urllib
import torch
from PIL import Image
from torchvision import transforms
import json
import random
import shap
import numpy as np
from keras.applications.vgg16 import preprocess_input

In [21]:
random_pics = random.sample(range(0, 50), 5)
print(random_pics)

[5, 46, 47, 9, 40]


In [22]:
model = torch.hub.load('pytorch/vision:v0.10.0', 'alexnet', pretrained=True)
X,y = shap.datasets.imagenet50()
to_explain = X[[random_pics]]

Using cache found in /Users/tobiaslabarta/.cache/torch/hub/pytorch_vision_v0.10.0
Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [23]:
# load the ImageNet class names
url = "https://s3.amazonaws.com/deep-learning-models/image-models/imagenet_class_index.json"
fname = shap.datasets.cache(url)
with open(fname) as f:
    class_names = json.load(f)

In [43]:
#run Gradient Explainer on Model
explainer = shap.GradientExplainer(model, transforms.totensor(X.copy())

shap_values,indexes = explainer.shap_values(to_explain, ranked_outputs=1)

SyntaxError: invalid syntax (4098086497.py, line 4)

In [28]:
# get the names for the classes
index_names = np.vectorize(lambda x: class_names[str(x)][1])(indexes)

NameError: name 'indexes' is not defined

In [29]:
# plot the explanations
shap.image_plot(shap_values=shap_values, pixel_values=to_explain, labels=index_names)

NameError: name 'shap_values' is not defined

In [34]:
print(X.copy())

[[[[ 33.  23.  24.]
   [ 72.  64.  61.]
   [ 68.  61.  53.]
   ...
   [ 86. 113. 158.]
   [124. 148. 182.]
   [ 41.  65. 103.]]

  [[ 63.  51.  51.]
   [ 23.  13.  11.]
   [ 38.  29.  22.]
   ...
   [ 77. 106. 150.]
   [ 94. 123. 163.]
   [ 72.  95. 137.]]

  [[ 29.  20.  13.]
   [ 37.  28.  19.]
   [ 64.  55.  46.]
   ...
   [ 83. 110. 153.]
   [ 94. 127. 170.]
   [131. 153. 194.]]

  ...

  [[ 98. 153. 122.]
   [ 72. 140. 103.]
   [ 49.  79.  53.]
   ...
   [207. 171.  75.]
   [ 78.  61.  15.]
   [ 56.  96.  72.]]

  [[ 92. 142. 113.]
   [ 72. 143. 103.]
   [ 53.  79.  52.]
   ...
   [249. 209. 114.]
   [116.  91.  35.]
   [ 62.  96.  71.]]

  [[ 96. 151. 122.]
   [ 67. 137. 101.]
   [ 58.  82.  58.]
   ...
   [250. 210. 114.]
   [124.  98.  41.]
   [ 47.  80.  53.]]]


 [[[117. 119. 116.]
   [113. 115. 112.]
   [111. 113. 110.]
   ...
   [ 40.  43.  22.]
   [ 41.  44.  23.]
   [ 39.  42.  21.]]

  [[117. 119. 116.]
   [114. 116. 113.]
   [111. 113. 110.]
   ...
   [ 41.  44.  23.]
 

In [38]:
print(preprocess_input(X.copy()))

[[[[ -79.939       -93.779       -90.68      ]
   [ -42.939003    -52.779       -51.68      ]
   [ -50.939003    -55.779       -55.68      ]
   ...
   [  54.060997     -3.7789993   -37.68      ]
   [  78.061        31.221         0.3199997 ]
   [  -0.939003    -51.779       -82.68      ]]

  [[ -52.939003    -65.779       -60.68      ]
   [ -92.939      -103.779      -100.68      ]
   [ -81.939       -87.779       -85.68      ]
   ...
   [  46.060997    -10.778999    -46.68      ]
   [  59.060997      6.2210007   -29.68      ]
   [  33.060997    -21.779       -51.68      ]]

  [[ -90.939       -96.779       -94.68      ]
   [ -84.939       -88.779       -86.68      ]
   [ -57.939003    -61.779       -59.68      ]
   ...
   [  49.060997     -6.7789993   -40.68      ]
   [  66.061        10.221001    -29.68      ]
   [  90.061        36.221         7.3199997 ]]

  ...

  [[  18.060997     36.221       -25.68      ]
   [  -0.939003     23.221       -51.68      ]
   [ -50.939003    -37.779

In [39]:
print(type(X))

<class 'numpy.ndarray'>
